### ISSUE TITLE
Example of how to use grdtrack

### ISSUE THREAD

**Issue by Afelumo1992** [gmt-china/gitalk#443]
I have both grd and xyz data, i want to use grdtrack to sample my grd data on the xyz data but I couldn't after many attempt. 
Please could you show an example on how to do this.
 Also how to sample the grd data at 10km on the xyz data. 
I tried this but didnt get it
Example 1
 gmt grdtrack -G400_1_4_2_400.grd heatflow.xyz -Af -E93/-20,109/-1+i10u+d -R93/109/-20/-1 > heat.xyz
Example 2
$ gmt grdtrack -G400_1_4_2_400.grd heatflow.xyz -Af -E+o+d+i10u+l -R93/109/-20/-1 > heat.xyz

Example 3
$ gmt grdtrack -G400_1_4_2_400.grd heatflow.xyz -Af -E+oaz+d+i10ku+lu -R93/109/-20/-1 > heat.xyz

**Comment by seisman** [comment]
I don't think grdtrack works on xyz data. You need convert your XYZ data to grid via xyz2grd first.

**Comment by Afelumo1992** [comment]
> I don't think grdtrack works on xyz data. You need convert your XYZ data to grid via xyz2grd first.

ok, but what I saw  on the gmt website on grdtrack shows I need xy file and a grid file. so that I can be able to sample or interpolate the grd file from the xyfile.
Can I see an example. 
I actually want to sample the grid from the xy file.  then plot a  figure  from it.
Many thanks, I appreciate more clarification.

**Comment by Afelumo1992** [comment]
grdtrack [ xyfile ] -Ggrd1 -Ggrd2 ... [ -Af|p|m|r|R[+l] ] [ -Clength[u]/ds[/spacing][+a][+v] ] [ -Ddfile ] [ -Eline[,line,...][+aaz][+d][+iinc[u]][+llength[u]][+nnp][+oaz][+rradius[u] ] [ -N ] [ -Rregion ] [ -Smethod/modifiers ] [ -T[radius[u]][+e|p]] [ -V[level] ] [ -Z ] [ -bbinary ] [ -dnodata ] [ -fflags ] [ -ggaps ] [ -hheaders ] [ -iflags ] [ -nflags ] [ -oflags ] [ -sflags ] [ -:[i|o] ]

this is from the gmt 5.3.2 version. but to set the parameters I dont know

**Comment by seisman** [comment]
This is not a good place to ask questions. Please post your question to https://forum.generic-mapping-tools.org/
